// g++ -std=c++17 src/test_wal.cpp -o test_wal && ./test_wal
//all these tests were generated by ai since i was too lazy to write these tests
#define WAL_NO_MAIN
#include "wal.cpp"
#include "../include/corrupt.h"

using namespace std;

bool phase1_verification()
{
    const string path = "test.wal";
    const vector<string> expected = {"hello arnav", "hello man", "phase 1 testing"};

    filesystem::remove(path);

    {
        wal::WAL w(path);
        for (const auto &rec : expected)
            w.append(rec);
        w.flush();
    }

    wal::WAL w2(path);

    bool pass = (w2.records() == expected);
    cout << (pass ? "PHASE 1 TEST: PASS" : "PHASE 1 TEST: FAIL") << endl;
    return pass;
}

bool phase2_verification()
{
    const string path = "test2.wal";
    filesystem::remove(path);

    {
        wal::WAL w(path);
        w.append("a1");
        w.append("a2");
        w.append("a3");
        w.flush();
    }

    {
        wal::WAL w(path);
        w.append("b1");
        w.append("b2");
        w.flush();
    }

    wal::WAL w(path);

    const vector<string> expected = {"a1", "a2", "a3", "b1", "b2"};

    bool content_ok = (w.records() == expected);
    bool lsn_ok = (w.next_lsn() == 6);

    bool pass = content_ok && lsn_ok;
    cout << (pass ? "PHASE 2 TEST: PASS" : "PHASE 2 TEST: FAIL") << endl;
    return pass;
}

bool phase3_verification()
{
    // flipped payload bit -> CRC mismatch
    {
        const string path = "test3a.wal";
        filesystem::remove(path);
        {
            wal::WAL w(path);
            w.append("good-0");
            w.append("good-1");
            w.append("good-2");
            w.flush();
        }

        fault::flip_payload_bit(path, 1);

        wal::WAL w(path);

        const vector<string> expected = {"good-0"};
        bool ok = (w.records() == expected);
        cout << (ok ? "  case A (bad CRC): PASS" : "  case A (bad CRC): FAIL") << endl;
        if (!ok)
            return false;
    }

    // truncated mid payload -> torn tail
    {
        const string path = "test3b.wal";
        filesystem::remove(path);
        {
            wal::WAL w(path);
            w.append("keep-0");
            w.append("keep-1");
            w.append("torn-2");
            w.flush();
        }

        fault::truncate_to(path, 2, sizeof(wal::RecordHeader) + 2);

        wal::WAL w(path);

        const vector<string> expected = {"keep-0", "keep-1"};
        bool ok = (w.records() == expected);
        cout << (ok ? "  case B (torn tail): PASS" : "  case B (torn tail): FAIL") << endl;
        if (!ok)
            return false;
    }

    cout << "PHASE 3 TEST: PASS" << endl;
    return true;
}

int main()
{
    bool p1 = phase1_verification();
    bool p2 = phase2_verification();
    bool p3 = phase3_verification();
    return (p1 && p2 && p3) ? 0 : 1;
}
